Repository Farama-Foundation/PettingZoo, pull requests merged in 2023-05, with the labels that each got.

#975 Remove casting actions to int in the Parallel -> AEC conversion
  pettingzoo/utils/conversions.py
Labels: bug

#964 Added type hints in utils package
  pettingzoo/utils/agent_selector.py
  pettingzoo/utils/average_total_reward.py
  pettingzoo/utils/capture_stdout.py
  pettingzoo/utils/conversions.py
  pettingzoo/utils/deprecated_module.py
  pettingzoo/utils/env.py
  pettingzoo/utils/env_logger.py
  pettingzoo/utils/random_demo.py
  pettingzoo/utils/save_observation.py
  pettingzoo/utils/wrappers/assert_out_of_bounds.py
  pettingzoo/utils/wrappers/base.py
  pettingzoo/utils/wrappers/base_parallel.py
  pettingzoo/utils/wrappers/capture_stdout.py
  pettingzoo/utils/wrappers/clip_out_of_bounds.py
  pettingzoo/utils/wrappers/order_enforcing.py
  pettingzoo/utils/wrappers/terminate_illegal.py
Labels: enhancement, in progress

#970 MPE fix agent dynamics
  docs/environments/mpe.md
  pettingzoo/mpe/_mpe_utils/core.py
  pettingzoo/mpe/simple/simple.py
  pettingzoo/mpe/simple_adversary/simple_adversary.py
  pettingzoo/mpe/simple_adversary_v3.py
  pettingzoo/mpe/simple_crypto/simple_crypto.py
  pettingzoo/mpe/simple_crypto_v3.py
  pettingzoo/mpe/simple_push/simple_push.py
  pettingzoo/mpe/simple_push_v3.py
  pettingzoo/mpe/simple_reference/simple_reference.py
  pettingzoo/mpe/simple_reference_v3.py
  pettingzoo/mpe/simple_speaker_listener/simple_speaker_listener.py
  pettingzoo/mpe/simple_speaker_listener_v4.py
  pettingzoo/mpe/simple_spread/simple_spread.py
  pettingzoo/mpe/simple_spread_v3.py
  pettingzoo/mpe/simple_tag/simple_tag.py
  pettingzoo/mpe/simple_tag_v3.py
  pettingzoo/mpe/simple_v3.py
  pettingzoo/mpe/simple_world_comm/simple_world_comm.py
  pettingzoo/mpe/simple_world_comm_v3.py
  pettingzoo/test/api_test.py
  pettingzoo/test/state_test.py
  test/all_modules.py
  test/all_parameter_combs_test.py
Labels: bug, in progress
