Repository Farama-Foundation/PettingZoo, pull requests merged in 2025-04, with the labels that each got.

#1282 Remove duplicate code in RLCard environments
  docs/_scripts/gen_envs_mds.py
  pettingzoo/classic/rlcard_envs/gin_rummy.py
  pettingzoo/classic/rlcard_envs/leduc_holdem.py
  pettingzoo/classic/rlcard_envs/rlcard_base.py
  pettingzoo/classic/rlcard_envs/rlcard_utils.py
  pettingzoo/classic/rlcard_envs/texas_holdem.py
  pettingzoo/classic/rlcard_envs/texas_holdem_no_limit.py
Labels: bug, enhancement

#1283 Explicitly export items
  pettingzoo/__init__.py
  pettingzoo/utils/__init__.py
  pettingzoo/utils/wrappers/__init__.py
Labels: enhancement

#1280 [FEAT]: Add deprecation warnings to MPE environment to prepare for their future migration to the MPE2 package
  docs/environments/mpe.md
  pettingzoo/mpe/__init__.py
  pettingzoo/mpe/simple/simple.py
  pettingzoo/mpe/simple_adversary/simple_adversary.py
  pettingzoo/mpe/simple_adversary_v3.py
  pettingzoo/mpe/simple_crypto/simple_crypto.py
  pettingzoo/mpe/simple_crypto_v3.py
  pettingzoo/mpe/simple_push/simple_push.py
  pettingzoo/mpe/simple_push_v3.py
  pettingzoo/mpe/simple_reference/simple_reference.py
  pettingzoo/mpe/simple_reference_v3.py
  pettingzoo/mpe/simple_speaker_listener/simple_speaker_listener.py
  pettingzoo/mpe/simple_speaker_listener_v4.py
  pettingzoo/mpe/simple_spread/simple_spread.py
  pettingzoo/mpe/simple_spread_v3.py
  pettingzoo/mpe/simple_tag/simple_tag.py
  pettingzoo/mpe/simple_tag_v3.py
  pettingzoo/mpe/simple_v3.py
  pettingzoo/mpe/simple_world_comm/simple_world_comm.py
  pettingzoo/mpe/simple_world_comm_v3.py
Labels: documentation, dependencies

#1290 [FIX]: fix build-publish
  .github/workflows/build-publish.yml
Labels: bug
