Repository Farama-Foundation/PettingZoo, pull requests merged in 2025-02, with the labels that each got.

#1246 [Feat] Deprecate Python 3.8, add Python 3.12 + update CI/CD
  .github/workflows/build-publish.yml
  .github/workflows/docs-test.yml
  .github/workflows/linux-test.yml
  .github/workflows/linux-tutorials-test.yml
  .github/workflows/macos-test.yml
  .gitignore
  README.md
  docs/content/basic_usage.md
  docs/tutorials/agilerl/index.md
  pyproject.toml
  tutorials/AgileRL/requirements.txt
  tutorials/CustomEnvironment/requirements.txt
Labels: documentation, enhancement, in progress, python

#1256 Update README.md
  README.md
Labels: enhancement

#1247 Fix #1225 by removing the wrong paragraph
  docs/api/aec.md
Labels: documentation

#1264 [Update] Update branch to new version of CI/CD
  .github/workflows/build-publish.yml
  .github/workflows/docs-test.yml
  .github/workflows/linux-test.yml
  .github/workflows/linux-tutorials-test.yml
  .github/workflows/macos-test.yml
  .gitignore
  README.md
  docs/api/aec.md
  docs/content/basic_usage.md
  docs/tutorials/agilerl/index.md
  pyproject.toml
  tutorials/AgileRL/requirements.txt
  tutorials/CustomEnvironment/requirements.txt
Labels: bug, documentation, enhancement, python, github_actions

#1268 Fix Github Workflow for Building Documentations
  .github/workflows/build-docs.yml
Labels: bug, github_actions

#1270 Fix pyright type error to assert that actions can't be an int.
  pettingzoo/utils/average_total_reward.py
  pettingzoo/utils/random_demo.py
Labels: bug, python
